version: '3.7'

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/data
    network_mode: host
    restart: unless-stopped
    container_name: nodered
    logging:
      options:
        max-size: 50m
